language: python
python:
    - "3.6"
env:
    - CODECOV_TOKEN="aebc8f34-b027-475f-9900-147a1e318e85"
before_install:
    - pip install -e .
    - pip install pytest pytest-qt pytest-xvfb codecov
script: pytest
notifications:
    # Telegram bot hook:
    webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
after_success:
    - codecov
